TrackerExpense/TrackerExpenseMVC/Controllers/CategoryEController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using TrackerExpenseMVC.Models;

namespace TrackerExpenseMVC.Controllers
{
    public class CategoryEController : Controller
    {
        // GET: CategoryE
        public ActionResult Index(int id)
        {
            IEnumerable<ExpenseMVC> expList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Expense").Result;
            expList = response.Content.ReadAsAsync<IEnumerable<ExpenseMVC>>().Result;
            var sai = expList.Where(p => p.CId == id).ToList();
            return View(sai);
        }
        public ActionResult Index1(int id)
        {
            IEnumerable<CategoryMVC> expList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Category").Result;
            expList = response.Content.ReadAsAsync<IEnumerable<CategoryMVC>>().Result;
            /*ViewBag.a=expList.Where(p=>p.CId==id).Select(p=>p.CName);*/
            var sai = expList.Where(p => p.CId == id).ToList();
            return View(sai);
        }
    }
}

TrackerExpense/TrackerExpenseMVC/Controllers/ExpenseTrackerController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using TrackerExpenseMVC.Models;

namespace TrackerExpenseMVC.Controllers
{
    public class ExpenseTrackerController : Controller
    {
        // GET: ExpenseTracker
            public ActionResult Index()
            {
                dynamic de = new ExpandoObject();
                de.expense = GetExpense();
                de.category = GetCategory();
            de.totalexpense= GetTotalExpense();
                return View(de);
            }
            public List<ExpenseMVC> GetExpense()
            {
                List<ExpenseMVC> expList;
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Expense").Result;
                expList = response.Content.ReadAsAsync<List<ExpenseMVC>>().Result;
            ViewBag.add = expList.Sum(a => a.Amount);
                return expList;
            }
            public List<CategoryMVC> GetCategory()
            {
                List<CategoryMVC> expList;
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Category").Result;
                expList = response.Content.ReadAsAsync<List<CategoryMVC>>().Result;
                return expList;

            }
            public List<TotalExpenseMVC> GetTotalExpense() 
            {
            List<TotalExpenseMVC> expList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("TotalExpense").Result;
            expList = response.Content.ReadAsAsync<List<TotalExpenseMVC>>().Result;
            return expList;

        }

    }
    }

TrackerExpense/TrackerExpenseMVC/Views/ExpenseTracker/Index.cshtml
@using TrackerExpenseMVC.Models;
@model dynamic
@{
    ViewBag.Title = "Index";
}
<br />
<html>
<head>
</head>
<body>
    <div><h1 style="color:#33006f"><b>Hello! Welcome  </b><small style="color:#c3b1e1">to my Expense Tracker</small></h1></div>
    <br />
    @*<h1>@ViewBag.add</h1>*@
   <div> <h2 style="float: left; font-size: 26px; color: #8d5192 ">The Expense List</h2>
    <a href="@Url.Action("Index","Expense")" class="btn button" style="background-color: #8d5192; color: white; float: right; margin-top: 20px ">Go to Expense</a>
    </div>
    <br />
    <br />
    <br />
    <table border="1" class="table table-striped table-hover" style="border-radius:10px;border: 4px solid #8d5192;">
        <tr style="background-color: #8d5192; color:white;height:25px;">
            <th>Title</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Category Name</th>
            <th>Action</th>
        </tr>
        @foreach (ExpenseMVC ex in Model.expense)
        {
            <tr>

                <td>
                    @ex.Title
                </td>
                <td>
                    @ex.Description
                </td>
                <td>
                    @ex.Amount
                </td>
                <td>
                    @foreach (CategoryMVC e in Model.category)
                    {
                        if (ex.CId == e.CId)
                        {
                            @e.CName}
                    }
                </td>
                <td><a href="@Url.Action("Index1", "CategoryE", new { id = ex.CId })" style="background-color: #8d5192;color:white;"class="btn btn-default"><i class="fa fa-pencil"></i>Get Category</a></td>
            </tr>
        }
    </table>
    <br />
    <div style="font-size: 18px; height: 28px; background-color: #dedede; color: #8d5192">
        The sum of all the expense amount is Rs.@ViewBag.add
    </div>
    <br />
    <br />

    <div><h2 style="float:left;color:#8d5192;font-size:26px;">The Category List</h2>
         <a href="@Url.Action("Index","Category")" class="btn button" style="background-color: #8d5192; color: white; float: right; margin-top: 20px ">Go to Category</a></div>
    <center>
        <table border="1" class="table table-stiped table-hover" style="border-radius:10px;border: 4px solid #8d5192;">
            <tr style="background-color: #8d5192; color:white;height:25px;">
                @*<th>Category ID</th>*@
                <th>Category Name</th>
                <th>Category Expense</th>
                <th>Action</th>
            </tr>
            @foreach (CategoryMVC ex in Model.category)
            {
                <tr>
                   @* <td>@ex.CId</td>*@
                    <td>@ex.CName</td>
                    <td>@ex.CExpenseLimit</td>
                    <td><a href="@Url.Action("Index", "CategoryE", new { id = ex.CId })" style="background-color: #8d5192;color:white" class="btn btn-default" ><i class="fa fa-pencil"></i>Get Expense</a></td>
                </tr>
            }
        </table>
    </center>
    <br />
    <br />

    <div>
        <h2 style="float:left;color:#8d5192;font-size:26px;">Total Expense List</h2>
        <a href="@Url.Action("Index","TotalExpense")" class="btn button" style="background-color: #8d5192; color: white; float: right; margin-top: 20px ">Go to Total Expense</a>
        </div>
        <br />
        <br /><br />


        <table border="1" class="table table-stiped table-hover navbar-static-top" style="border-radius:10px;border: 4px solid #8d5192;">
            <tr style="background-color: #8d5192; color:white;height:25px;">
                <th>Total Expense Limit</th>
            </tr>
            @foreach (TotalExpenseMVC ex in Model.totalexpense)
            {
                <tr>
                    <td>@ex.TExpenseLimit</td>
                </tr>
            }
        </table>

        @*<a href="https://localhost:44366/expense">Expense</a>
        <a href="https://localhost:44366/category">Category</a>*@
</body>
</html>