TrackerExpense/TrackerExpenseMVC/Controllers/ExpenseTrackerController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using TrackerExpenseMVC.Models;

namespace TrackerExpenseMVC.Controllers
{
    public class ExpenseTrackerController : Controller
    {
        // GET: ExpenseTracker
            public ActionResult Index()
            {
                dynamic de = new ExpandoObject();
                de.expense = GetExpense();
                de.category = GetCategory();
            de.totalexpense= GetTotalExpense();
                return View(de);
            }
            public List<ExpenseMVC> GetExpense()
            {
                List<ExpenseMVC> expList;
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Expense").Result;
                expList = response.Content.ReadAsAsync<List<ExpenseMVC>>().Result;
            ViewBag.add = expList.Sum(a => a.Amount);
                return expList;
            }
            public List<CategoryMVC> GetCategory()
            {
                List<CategoryMVC> expList;
                HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Category").Result;
                expList = response.Content.ReadAsAsync<List<CategoryMVC>>().Result;
                return expList;

            }
            public List<TotalExpenseMVC> GetTotalExpense() 
            {
            List<TotalExpenseMVC> expList;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("TotalExpense").Result;
            expList = response.Content.ReadAsAsync<List<TotalExpenseMVC>>().Result;
            return expList;

        }

    }
    }

TrackerExpense/TrackerExpenseMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />
    <style>
        body{
            font-family:'Poppins',sans-serif;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top"  style="background-color:#8d5192; color:white;">
        <div class="container" style="color:white">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Expense Tracker", "Index", "ExpenseTracker", new { area = "" }, new { @class = "navbar-brand" })*@
                <a   href="https://localhost:44366/expensetracker" class="navbar-brand" style="font-size:17px;position:absolute;right:1280px;color:white;">Expense Tracker</a>
                <a   href="https://localhost:44366/expense" class="navbar-brand" style="font-size: 17px; position: absolute; right: 550px; color: white;">Expense</a>
                <a   href="https://localhost:44366/category" class="navbar-brand" style="font-size: 17px; position: absolute; right: 440px; color: white; ">Category</a>
                <a   href="https://localhost:44366/totalexpense" class="navbar-brand" style="font-size: 17px; position: absolute; right: 300px; color: white;">Total Expense</a>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p> &#9829 From Anisha Singh</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/alertify.min.js"></script>
    @RenderSection("scripts", required: false)
    
</body>
</html>